---
- name: Create VPC
  ec2_vpc_net:
      cidr_block: "{{ vpc_cidr_block }}"
      dns_hostnames: yes
      dns_support: yes
      multi_ok: no
      name: "{{ vpc_name }}"
      region: "{{ vpc_region }}"
      state: "{{ vpc_state }}"
      tenancy: "default"
      tags:
          Name: "{{ vpc_name }}"
          Project: "{{ vpc_project }}"
          Purpose: "{{ vpc_purpose }}"
          Creator: "{{ vpc_creator }}"
          Environment: "{{ vpc_environment }}"
          Freetext: "{{ vpc_freetext }}"
  register: vpc_result

- name: Store VPC ID
  set_fact:
    vpc_id: "{{ vpc_result.vpc.id }}"

- name: Gather Route Table Facts
  ec2_vpc_route_table_facts:
      region: "{{ vpc_region }}"
      filters:
          vpc-id: "{{ vpc_result.vpc.id }}"
  register: route_table_result

- name: Store Default Route Table ID
  set_fact:
    default_route_table_id: "{{ route_table_result.route_tables[0].id }}"

- debug:
    msg: "Result is {{ default_route_table_id }}"

- name: Tag Default Route Table ID
  ec2_vpc_route_table:
      region: "{{ vpc_region }}"
      vpc_id: "{{ vpc_id }}"
      route_table_id: "{{ default_route_table_id }}"
      tags:
          Name: "{{ vpc_name }}"
          Project: "{{ vpc_project }}"
          Purpose: "{{ vpc_purpose }}"
          Creator: "{{ vpc_creator }}"
          Environment: "{{ vpc_environment }}"
          Freetext: "VPC's default route table"
