---
- name: Create VPC
  ec2_vpc_net:
      cidr_block: "{{ vpc_cidr_block }}"
      dns_hostnames: yes
      dns_support: yes
      multi_ok: no
      name: "{{ vpc_name }}"
      region: "{{ vpc_region }}"
      state: "{{ vpc_state }}"
      tenancy: "default"
      tags:
          Name: "{{ vpc_name }}"
          Project: "{{ vpc_project }}"
          Purpose: "{{ vpc_purpose }}"
          Creator: "{{ vpc_creator }}"
          Environment: "{{ vpc_environment }}"
          Freetext: "{{ vpc_freetext }}"
  when: vpc_create
